---
title: "Semi-quantitative evaluation of access and coverage"
author: "Ernest Guevarra"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Semi-quantitative evaluation of access and coverage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

In the recent past, measurement of coverage has been mainly through two-stage cluster sampled surveys either as part of a nutrition assessment or through a specific coverage survey known as Centric Systematic Area Sampling (CSAS). However, such methods are resource intensive and often only used for final programme evaluation meaning results arrive too late for programme adaptation. SQUEAC, which stands for Semi-Quantitative Evaluation of Access and Coverage, is a low resource method designed specifically to address this limitation and is used regularly for monitoring, planning and importantly, timely improvement to programme quality, both for agency and Ministry of Health (MoH) led programmes. This package provides functions for use in conducting a SQUEAC investigation.

## What does `squeacr` do?

The `{squeacr}` package provides functions that facilitate the processing, analysis and reporting of various components of a SQUEAC investigation. The current version of the `{squeacr}` package currently provides the following:

* Functions to calculate CMAM programme performance metrics;

* Functions to calculate CMAM programme length of stay metrics; and,

* Functions to calculate CMAM coverage estimates.

## Installation

The `{squeacr}` package is not yet available on [CRAN](https://cran.r-project.org) but can be installed from the [nutriverse R Universe](https://nutriverse.r-universe.dev) as follows:

```{r install, echo = TRUE, eval = FALSE}
install.packages(
  "squeacr",
  repos = c('https://nutriverse.r-universe.dev', 'https://cloud.r-project.org')
)
```

